const colors = {
  transparent: 'transparent',
  white: '#ffffff',
  veryLightPinkThree: '#f2f2f2',
  brownGrey: '#7B7B7B',
  taupeGray: '#888888',
  brownishGrey: '#5A5A5A',
  veryLightPinkFour: '#E6E6E6',
  robinSEgg: '#5adbff',
  purpley: '#7764e4',
  veryLightPink: '#cecece',
  veryLightPinkTwo: '#efefef',
  brightRed: '#F76C6C',
  matterhorn: '#4b4b4b',
  lightCyan: '#E5F9FF',
  seashell: '#FFF3E5',
  magnolia: '#F7E5FF',
  pumpkinOrange: '#ff9b26',
  brightPurple: '#BC25FF',
  caramel: '#ffd19d',
  mauve: '#e19dff',
  grapeFruit: '#ff5353',
  brightSkyBlue: '#00c7ff',
  vibrantBlue: '#0045ff',
  darkSlateBlue: '#172b4d',
  blueyGrey: '#8898aa',
  deepSkyBlue: '#0076FF',
  aliceBlue: '#e5f1ff',
  columbiaBlue: '#9ECAFF',
  cornflowerBlue: '#a3eaff',
  brightSeaGreen: '#00ffa7',
  caribbeanGreen: '#9de9ff',
  mediumSpringGreen: '#09ECAF',
  grapefruit: '#FF5353',
};

export default colors;
